LOCK_DIR: '/efs/deploy'
BUCKET: 'YOUR-HANDLE-phpuk-deploy'
SNS_SUCCESS: 'arn:aws:sns:eu-west-1:<AWS-ID>:ec2-web-deploy-success'
SNS_ERROR: 'arn:aws:sns:eu-west-1:<AWS-ID>:ec2-web-deploy-error'
OWNER: 'www-data'
NICKNAME: 'whatever-you-want'
DOMAIN: 'phpuk-YOUR-HANDLE.1webservices.co.uk'
CMD:
